#!/bin/bash

factorize() {
    num=$1
    divisor=2
    factors=()
    while [ $num -gt 1 ]; do
        while [ $(($num % $divisor)) -eq 0 ]; do
            factors+=($divisor)
            num=$(($num / $divisor))
        done
        divisor=$((divisor + 1))
    done
    echo "${factors[@]}"
}

main() {
    filename=$1
    while IFS= read -r line; do
        num="$line"
        factors=$(factorize "$num")
        echo "$num=${factors[*]}"
    done < "$filename"
}

main "$1"

